nome = input("Digite seu nome")
idade = input("digite sua idade: ")
sexo = input("digite o genero: ")
endereço = input("Digite seu endereço: ")
telefone = input("Digite seu telefone: ")

print ("Nome: \n" ,nome)
print ("Idade: \n" ,idade)
print ("Genero: \n", sexo)
print ("Endereço:\n",endereço)
print ("Telefone: \n", telefone)
